### ISSUE TITLE
ModuleNotFoundError: No module named 'ppadb'

### ISSUE THREAD

**Issue by MarxistBun** [yuceltoluyag/Rise-of-Kingdoms-Bot#10]
PS C:\Users\Admin\Desktop\Rise-of-Kingdoms-Bot-0.0.1-Beta> python mail.py
C:\Users\Admin\AppData\Local\RLBotGUIX\Python37\python.exe: can't open file 'mail.py': [Errno 2] No such file or directory
PS C:\Users\Admin\Desktop\Rise-of-Kingdoms-Bot-0.0.1-Beta> python main.py
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import adb
  File "C:\Users\Admin\Desktop\Rise-of-Kingdoms-Bot-0.0.1-Beta\adb.py", line 1, in <module>
    from ppadb.client import Client as PPADBClient
ModuleNotFoundError: No module named 'ppadb'
PS C:\Users\Admin\Desktop\Rise-of-Kingdoms-Bot-0.0.1-Beta>

**Comment by yuceltoluyag** [comment]
Incorrect usage `python main.py` : )  https://github.com/yuceltoluyag/Rise-of-Kingdoms-Bot/issues/5#issuecomment-1577295867
