### ISSUE TITLE
py main.py doesent work

### ISSUE THREAD

**Issue by papi-pap-dolo** [yuceltoluyag/Rise-of-Kingdoms-Bot#14]
### What happened?

hello, im getting this error, how do i fix it

### Package version used

0.0.1

### Please provide information about your operating system

Windows 11 Home 64bit 23H2

### Please provide information about your emulator

Blue Stack 

### Please provide information about your python version

3.12.0

### Relevant log output

```shell
C:\Users\logmy\OneDrive\Pulpit\Rise-of-Kingdoms-Bot-0.0.1>py main.py
Traceback (most recent call last):
  File "C:\Users\logmy\OneDrive\Pulpit\Rise-of-Kingdoms-Bot-0.0.1\main.py", line 1, in <module>
    import adb
  File "C:\Users\logmy\OneDrive\Pulpit\Rise-of-Kingdoms-Bot-0.0.1\adb.py", line 1, in <module>
    from ppadb import Client as PPADBClient
ImportError: cannot import name 'Client' from 'ppadb' (C:\Users\logmy\AppData\Local\Programs\Python\Python312\Lib\site-packages\ppadb\__init__.py)
```

**Comment by yuceltoluyag** [comment]
> 3.12.0

I have not tried with the latest version of python. Although the recommended version is 3.9, I am using Python version 3.11.4. If you have done everything correctly, there may be an incompatibility problem.  you can check here. https://github.com/yuceltoluyag/Rise-of-Kingdoms-Bot/issues/5

```
pip install -r requirements.txt
pip install --upgrade ppadb
```
