### ISSUE TITLE
healing troops does not work

### ISSUE THREAD

**Issue by JefIra24** [yuceltoluyag/Rise-of-Kingdoms-Bot#15]
when I bot to attack the barbarian, for the problem of healing the troops, he doesn't press HEAL...
how to handle it

**Comment by yuceltoluyag** [comment]
Yes, I touched on that there. https://github.com/yuceltoluyag/Rise-of-Kingdoms-Bot/pull/13  

If your resolution is correct, download this button and change it.  [Heal Button](https://github.com/yuceltoluyag/Rise-of-Kingdoms-Bot/blob/35774eddcc899fa64caa79f12014ad2077b31b4f/resource/heal_icon.png)

If it still doesn't work, take this picture yourself and save it in the same directory with the same name (from the in-game screen just take a picture of the heal  icon...)

I'm sorry I didn't have time for this project. I apologise for the late reply
