### ISSUE TITLE
libpng warning: sBIT: invalid

### ISSUE THREAD

**Issue by Arcanic343** [yuceltoluyag/Rise-of-Kingdoms-Bot#18]
### What happened?

When I click start it gives me error: libpng warning: sBIT: invalid , and enters a quit loop from the game (I have already entered the captcha key).

### Package version used

0.0.1

### Please provide information about your operating system

Windows 10 Pro

### Please provide information about your emulator

LDPLAYER9

### Please provide information about your python version

3.12.3

### Relevant log output

```shell
libpng warning: sBIT: invalid
libpng warning: sBIT: invalid
libpng warning: sBIT: invalid
libpng warning: sBIT: invalid
libpng warning: sBIT: invalid
libpng warning: sBIT: invalid
libpng warning: sBIT: invalid
libpng warning: sBIT: invalid
libpng warning: sBIT: invalid
libpng warning: sBIT: invalid
libpng warning: sBIT: invalid
libpng warning: sBIT: invalid
libpng warning: sBIT: invalid
```

**Comment by yuceltoluyag** [comment]
https://github.com/yuceltoluyag/Rise-of-Kingdoms-Bot/issues/12
https://github.com/yuceltoluyag/Rise-of-Kingdoms-Bot/pull/13
