### ISSUE TITLE
hı ı cant start the bot (No module named 'ppadb') eror

### ISSUE THREAD

**Issue by eren3323** [yuceltoluyag/Rise-of-Kingdoms-Bot#25]
### What happened?

No module named 'ppadb'

### Package version used

0.0.1

### Please provide information about your operating system

11pro

### Please provide information about your emulator

last

### Please provide information about your python version

last

### Relevant log output

```shell
No module named 'ppadb'
```

**Comment by JasserRomero** [comment]
Did you install the dependencies? (requirements.txt) @eren3323

**Comment by yuceltoluyag** [comment]
https://github.com/yuceltoluyag/Rise-of-Kingdoms-Bot/issues/5#issuecomment-1577295867
https://github.com/yuceltoluyag/Rise-of-Kingdoms-Bot/issues/14
