### ISSUE TITLE
pass verification  Not Working

### ISSUE THREAD

**Issue by Usamarajputrok** [yuceltoluyag/Rise-of-Kingdoms-Bot#4]
Sir it’s showing cannot pass verification stopping bot now

**Comment by yuceltoluyag** [comment]
https://github.com/yuceltoluyag/Rise-of-Kingdoms-Bot#functions I wrote in this section that it is currently not working. I guess you didn't see it.

Will there be an update for the bot? I don't know for now. I work a lot (my main job is not to develop software) and I am reluctant. I might add a day. I didn't have much to do with the API, as I usually open the bot while I'm at the computer. The only reason for users to be banned is to verify the images with the api. If possible, use the bot while at the computer, stop the bot when the verification screen comes up and verify manually.

**Comment by Usamarajputrok** [comment]
@ndhao164  thanks sir please fix it

**Comment by ndhao164** [comment]
@Usamarajputrok check it https://github.com/yuceltoluyag/Rise-of-Kingdoms-Bot/pull/7

**Comment by yuceltoluyag** [comment]
https://github.com/yuceltoluyag/Rise-of-Kingdoms-Bot/releases/tag/0.0.1-Beta  Thanks for your support, I can't be at the computer much. I published your codes as a test if anyone wants to try https://github.com/yuceltoluyag/Rise-of-Kingdoms-Bot/releases/tag/0.0.1-Beta
